name: Magento 2 CI Pipeline

on:
  push:
    branches:
      - main
      - develop

  pull_request:

jobs:

  magento-validation:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3
          extensions: mbstring, intl, pdo_mysql, soap, bcmath
          coverage: none

      - name: Check PHP Syntax
        run: find src/app/code -name "*.php" -exec php -l {} \;

      - name: Magento Coding Standard
        run: |
          composer global require magento/magento-coding-standard
          ~/.composer/vendor/bin/phpcs app/code --standard=Magento2

      - name: PHPStan Static Analysis
        run: |
          composer require --dev phpstan/phpstan
          vendor/bin/phpstan analyse app/code --level=5
